import Head from 'next/head'
import Image from 'next/image'
import About from '../components/Sections/Home/About/About'
import Banner from '../components/Sections/Home/Banner/Banner'
import Delivery from '../components/Sections/Home/Delivery/Delivery'
import Menu from '../components/Sections/Home/Menus/Menu'

export default function Home() {
  return (
    <div>
      <Head>
        <title>MyFood</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Banner/>
       <About/>
       <Delivery/>
       <Menu/>
      </main>

    </div>
  )
}
